name: Always Demo
on:
  workflow_dispatch: 
  # workflow_call:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  demo-always:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Always Demo 1
      run: exit 1
    - name: Always Demo 2
      if: always()
      run: echo "testing"
  demo-continue:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Continue Demo 1
      continue-on-error: true
      run: exit 1
    - name: Continue Demo 2
      if: always()
      run: echo "testing"
  
