name: Always Demo

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Always Demo 1
      continue-on-error: true
      run: exit 1
    - name: Always Demo 2
      if: always()
      run: 
