name: Common Demo
description: Demonstrating continue-on-error
on:
  workflow_dispatch:
  push:
    branches: [ "demo" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Common Demo
      continue-on-error: true
      run: 
    - name: The end
      run: echo "Finished"
